/**
 * Adam OS pixel icon set: one hand-made 16x16 pixel-art language for the whole UI.
 *
 * Each icon is 16 rows of 16 characters. Characters are colour ROLES, not colours,
 * so the icons follow the active theme (see <PixelIcon/>):
 *   .  transparent        k  outline (--c-shade)
 *   w  highlight (--c-hilite)   a  accent (--c-spidey)
 *   l  light accent (--c-lavender)   g  green   r  red   y  yellow
 *   s  grey (--c-slate)   d  dark grey (#4a4a5a)
 *   c  currentColor (UI glyphs such as close/minimize that should match text)
 *
 * This file is the single source of truth: scripts/icons/render_icons.py parses
 * these rows to bake the desktop PNGs in public/icons/app-*.png.
 */

export const PIXEL_ICON_NAMES = [
  'about',
  'projects',
  'skills',
  'lab',
  'resume',
  'pdf',
  'contact',
  'terminal',
  'explorer',
  'folder-open',
  'jukebox',
  'paint',
  'settings',
  'snake',
  'minesweeper',
  'search',
  'mail',
  'download',
  'web',
  'sound-on',
  'sound-off',
  'github',
  'link',
  'copy',
  'send',
  'power',
  'restart',
  'image',
  'desktop',
  'start',
  'close',
  'minimize',
  'maximize',
  'restore',
  'check',
  'warning',
  'info',
  'star',
  'spider',
  'trophy',
  'clock',
  'language',
  'calendar',
  'chip',
  'pin',
] as const;

export type IconName = (typeof PIXEL_ICON_NAMES)[number];

export type PixelRole = '.' | 'k' | 'w' | 'a' | 'l' | 'g' | 'r' | 'y' | 's' | 'd' | 'c';

export interface PixelIconDef {
  size: 16;
  rows: string[];
}

export const PIXEL_ICONS: Record<IconName, PixelIconDef> = {
  'about': {
    size: 16,
    rows: [
      '................',
      '................',
      'kkkkkkkkkkkkkkkk',
      'kaaaaaaaaaaaaaak',
      'kaaaaaawwaaaaaak',
      'kwwwwwwwwwwwwwwk',
      'kwkkkkkwwwwwwwwk',
      'kwklylkwddddddwk',
      'kwklylkwwwwwwwwk',
      'kwkaaakwdddddwwk',
      'kwkaaakwwwwwwwwk',
      'kwkkkkkwddddwwwk',
      'kwwwwwwwwwwwwwwk',
      'kkkkkkkkkkkkkkkk',
      '................',
      '................',
    ],
  },
  'projects': {
    size: 16,
    rows: [
      '................',
      '................',
      '................',
      '....kkkkkkkk....',
      '....kskkkksk....',
      '....ksk..ksk....',
      'kkkkkkkkkkkkkkkk',
      'kwwrrrrrrrrrrrrk',
      'krrrrrrrrrrrrrrk',
      'kkkkkkkkkkkkkkkk',
      'krrrrrkyykrrrrrk',
      'krrrrrkyykrrrrrk',
      'krrrrrrkkrrrrrrk',
      'krrrrrrrrrrrrrrk',
      'kkkkkkkkkkkkkkkk',
      '................',
    ],
  },
  'skills': {
    size: 16,
    rows: [
      '................',
      '....s.s..s.s....',
      '....s.s..s.s....',
      '..kkkkkkkkkkkk..',
      'sskddddddyyydkss',
      '..kdddddyyyddk..',
      'sskddddyyydddkss',
      '..kdddyyyyyydk..',
      '..kdddddyydddk..',
      'sskddddyyddddkss',
      '..kdddyydddddk..',
      'sskddydddddddkss',
      '..kkkkkkkkkkkk..',
      '....s.s..s.s....',
      '....s.s..s.s....',
      '................',
    ],
  },
  'lab': {
    size: 16,
    rows: [
      '................',
      '..a..........a..',
      '.a..a......a..a.',
      '.a.a..krrk..a.a.',
      '.a..a.krrk.a..a.',
      '..a....kk....a..',
      '.......kk.......',
      '.kkkkkkkkkkkkkk.',
      '.kggggggggggggk.',
      '.kgkkkkkkgggrgk.',
      '.kgkwssskgkkggk.',
      '.kgksssskgkkggk.',
      '.kgkkkkkkgggggk.',
      '.kggggggggggggk.',
      '.kkkkkkkkkkkkkk.',
      '..y.y.y.y.y.y...',
    ],
  },
  'resume': {
    size: 16,
    rows: [
      '..kkkkkkkkk.....',
      '..kwwwwwwwkk....',
      '..kwwwwwwwksk...',
      '..kwwwwwwwkssk..',
      '..kwwwwwwwkkkk..',
      '..kwaaaaaawwwk..',
      '..kwwwwwwwwwwk..',
      '..kwsssssssswk..',
      '..kwwwwwwwwwwk..',
      '..kwsssssssswk..',
      '..kwwwwwwwwwwk..',
      '..kwsssssssswk..',
      '..kwwwwwwwwwwk..',
      '..kwssssswwwwk..',
      '..kwwwwwwwwwwk..',
      '..kkkkkkkkkkkk..',
    ],
  },
  'pdf': {
    size: 16,
    rows: [
      '..kkkkkkkkk.....',
      '..kwwwwwwwkk....',
      '..kwwwwwwwksk...',
      '..kwwwwwwwkssk..',
      '..kwwwwwwwkkkk..',
      '..kwsssssssswk..',
      '..kwwwwwwwwwwk..',
      'kkkkkkkkkkkkkkk.',
      'krwwwrwwrrwwwrk.',
      'krwrwrwrwrwrrrk.',
      'krwwwrwrwrwwrrk.',
      'krwrrrwrwrwrrrk.',
      'krwrrrwwrrwrrrk.',
      'kkkkkkkkkkkkkkk.',
      '..kwwwwwwwwwwk..',
      '..kkkkkkkkkkkk..',
    ],
  },
  'contact': {
    size: 16,
    rows: [
      '................',
      '................',
      'kkkkkkkkkkkkkkkk',
      'kkllllllllllllkk',
      'kwkllllllllllkwk',
      'kwwkllllllllkwwk',
      'kwwwkllllllkwwwk',
      'kwwwwkllllkwwwwk',
      'kwwwwwkrrkwwwwwk',
      'kwwwwkrrrrkwwwwk',
      'kwwwkwkrrkwkwwwk',
      'kwwkwwwkkwwwkwwk',
      'kwkwwwwwwwwwwkwk',
      'kkkkkkkkkkkkkkkk',
      '................',
      '................',
    ],
  },
  'terminal': {
    size: 16,
    rows: [
      '................',
      'kkkkkkkkkkkkkkkk',
      'kaaaaaaaaaaawkwk',
      'kkkkkkkkkkkkkkkk',
      'kssssssssssssssk',
      'kskkkkkkkkkkkksk',
      'kskggkkkkkkkkksk',
      'kskkggkkkkkkkksk',
      'kskkkggkkkkkkksk',
      'kskkggkkkkkkkksk',
      'kskggkkggggkkksk',
      'kskkkkkkkkkkkksk',
      'kssssssssssssssk',
      'kkkkkkkkkkkkkkkk',
      '................',
      '................',
    ],
  },
  'explorer': {
    size: 16,
    rows: [
      '................',
      '................',
      '................',
      '.kkkkk..........',
      'kwyyyyk.........',
      'kyyyyyykkkkkkkk.',
      'kwwwwwwwwwwwwyk.',
      'kwyyyyyyyyyyyyk.',
      'kwyyyyyyyyyyyyk.',
      'kwyyyyyyyyyyyyk.',
      'kwyyyyyyyyyyyyk.',
      'kwyyyyyyyyyyyyk.',
      'kyyyyyyyyyyyyyk.',
      'kkkkkkkkkkkkkkk.',
      '................',
      '................',
    ],
  },
  'folder-open': {
    size: 16,
    rows: [
      '................',
      '................',
      '................',
      '.kkkkk..........',
      'kwyyyyk.........',
      'kyyyyyykkkkkk...',
      'kyyyyyyyyyyyk...',
      'kyykkkkkkkkkkkkk',
      'kyykwwwwwwwwwwk.',
      'kykwyyyyyyyyyyk.',
      'kykyyyyyyyyyyk..',
      'kkyyyyyyyyyyyk..',
      'kkyyyyyyyyyyk...',
      'kkkkkkkkkkkkk...',
      '................',
      '................',
    ],
  },
  'jukebox': {
    size: 16,
    rows: [
      '................',
      '................',
      '................',
      'kkkkkkkkkkkkkkkk',
      'kddddddddddddddk',
      'kdwwwwwwwwwwwwdk',
      'kdaaaaaaaaaaaadk',
      'kdwkkkkkkkkkkwdk',
      'kdwkwwsssswwkwdk',
      'kdwkwksssskwkwdk',
      'kdwkkkkkkkkkkwdk',
      'kdwwwwwwwwwwwwdk',
      'kddksssssssskddk',
      'kkkkkkkkkkkkkkkk',
      '................',
      '................',
    ],
  },
  'paint': {
    size: 16,
    rows: [
      '.............kkk',
      '.............kyk',
      '.............kyk',
      '...kkkkkkk...kyk',
      '..kwwwwwwwkk.kyk',
      '.kwrrwwyywwwkkyk',
      'kwwrrwwyywwwkksk',
      'kwwwwwwwwwwwkksk',
      'kwggwwwkkwwk.kdk',
      'kwggwwwkkwwk.kdk',
      'kwwwwwwwwwk..kak',
      '.kaawwwwwk....k.',
      '..kaawwwk.......',
      '...kkkkk........',
      '................',
      '................',
    ],
  },
  'settings': {
    size: 16,
    rows: [
      '.......kk.......',
      '.......kk.......',
      '...k...kk...k...',
      '..kskkksskkksk..',
      '...kswwsssssk...',
      '...kwwskksssk...',
      '...kwsk..kssk...',
      'kkkssk....ksskk.',
      'kkkssk....ksskk.',
      '...kssk..kssk...',
      '...kssskksssk...',
      '...kssssssssk...',
      '..kskkksskkksk..',
      '...k...kk...k...',
      '.......kk.......',
      '................',
    ],
  },
  'snake': {
    size: 16,
    rows: [
      '................',
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kggggggggwkk..',
      '..kggggggggggkrr',
      '..kggkkkkkkkkk..',
      '..kggggggggggk..',
      '..kggggggggggk..',
      '..kkkkkkkkkggk..',
      '...kkggggggggk..',
      '.kkggggggggggk..',
      '.kkkkkkkkkkkkk..',
      '................',
      '................',
      '................',
    ],
  },
  'minesweeper': {
    size: 16,
    rows: [
      'wwwwwwwwwwwwwwwd',
      'wssssssssssssssd',
      'wssssssskssssssd',
      'wssssssskssssssd',
      'wssskskkkkkskssd',
      'wsssskkkkkkksssd',
      'wssskkwwkkkkkssd',
      'wssskkwwkkkkkssd',
      'wskkkkkkkkkkkkkd',
      'wssskkkkkkkkkssd',
      'wssskkkkkkkkkssd',
      'wsssskkkkkkksssd',
      'wssskskkkkkskssd',
      'wssssssskssssssd',
      'wssssssskssssssd',
      'dddddddddddddddd',
    ],
  },
  'search': {
    size: 16,
    rows: [
      '................',
      '....kkkkk.......',
      '...ksssssk......',
      '..ksslllssk.....',
      '.ksswwlllssk....',
      '.kslwlllllsk....',
      '.kslllllllsk....',
      '.kslllllllsk....',
      '.ksslllllssk....',
      '..ksslllssk.....',
      '...kssssskkk....',
      '....kkkkk.kdk...',
      '...........kdk..',
      '............kdk.',
      '.............kk.',
      '................',
    ],
  },
  'mail': {
    size: 16,
    rows: [
      '................',
      '................',
      '................',
      '................',
      '.kkkkkkkkkkkkkk.',
      '.kkwwwwwwwwwwkk.',
      '.kwkwwwwwwwwkwk.',
      '.kwwkwwwwwwkwwk.',
      '.kwwwkwwwwkwwwk.',
      '.kwwwwkwwkwwwwk.',
      '.kwwwwwkkwwwwwk.',
      '.kwwwwwwwwwwwwk.',
      '.kkkkkkkkkkkkkk.',
      '................',
      '................',
      '................',
    ],
  },
  'download': {
    size: 16,
    rows: [
      '................',
      '................',
      '......kkkk......',
      '......kggk......',
      '......kggk......',
      '......kggk......',
      '......kggk......',
      '...kkkkggkkkk...',
      '....kggggggk....',
      '.....kggggk.....',
      'ksk...kggk...ksk',
      'ksk....kk....ksk',
      'kskkkkkkkkkkkksk',
      'kssssssssssssssk',
      'kkkkkkkkkkkkkkkk',
      '................',
    ],
  },
  'web': {
    size: 16,
    rows: [
      '................',
      '....kkkkkkkk....',
      '...kalallalak...',
      '..klwllllllllk..',
      '.kaggaallaggaak.',
      '.kagggallaaggak.',
      '.kggggallaalgak.',
      '.kllllllllllllk.',
      '.kaaggallaalaak.',
      '.kaalggllagggak.',
      '.kaalggllaaggak.',
      '.kaalaallaagaak.',
      '..kllllllllllk..',
      '...kalallalak...',
      '....kkkkkkkk....',
      '................',
    ],
  },
  'sound-on': {
    size: 16,
    rows: [
      '................',
      '................',
      '.......k........',
      '......kk........',
      '.....kwk...a....',
      'kkkkkwsk....a...',
      'kwsskssk.a...a..',
      'kwsskssk..a..a..',
      'kwsskssk..a..a..',
      'kwsskssk.a...a..',
      'kkkkkssk....a...',
      '.....ksk...a....',
      '......kk........',
      '.......k........',
      '................',
      '................',
    ],
  },
  'sound-off': {
    size: 16,
    rows: [
      '................',
      '................',
      '.......k........',
      '......kk........',
      '.....kwk........',
      'kkkkkwsk.rr...rr',
      'kwsskssk..rr.rr.',
      'kwsskssk...rrr..',
      'kwsskssk...rrr..',
      'kwsskssk..rr.rr.',
      'kkkkkssk.rr...rr',
      '.....ksk........',
      '......kk........',
      '.......k........',
      '................',
      '................',
    ],
  },
  'github': {
    size: 16,
    rows: [
      '................',
      '..kk........kk..',
      '..kdk......kdk..',
      '..kddkkkkkkddk..',
      '.kddddddddddddk.',
      '.kdlllllllllldk.',
      '.kdlkkllllkkldk.',
      '.kdlkkllllkkldk.',
      '.kdllllkklllldk.',
      '.kddllllllllddk.',
      '..kddddddddddk..',
      '...kkddddddkk...',
      '....kddddddk....',
      '...kddkddkddk...',
      '...kkk.kk.kkk...',
      '................',
    ],
  },
  'link': {
    size: 16,
    rows: [
      '................',
      '........kkkkkkk.',
      '........kkkaaak.',
      '...........kaak.',
      '.kkkkkkk..kakak.',
      '.kwwwww..kak.kk.',
      '.kwwwww.kak..kk.',
      '.kwwwwwkak...kk.',
      '.kwwwwkak..k....',
      '.kwwwkakwwwk....',
      '.kwwwkkwwwwk....',
      '.kwwwwwwwwwk....',
      '.kwwwwwwwwwk....',
      '.kwwwwwwwwwk....',
      '.kkkkkkkkkkk....',
      '................',
    ],
  },
  'copy': {
    size: 16,
    rows: [
      '................',
      '.kkkkkkkkk......',
      '.kwwwwwwwk......',
      '.kwssssswk......',
      '.kwwwwwwwk......',
      '.kwssskkkkkkkkk.',
      '.kwwwwkwwwwwwwk.',
      '.kwsssklllllwwk.',
      '.kwwwwkwwwwwwwk.',
      '.kwsssksssssswk.',
      '.kkkkkkwwwwwwwk.',
      '......ksssssswk.',
      '......kwwwwwwwk.',
      '......ksssswwwk.',
      '......kwwwwwwwk.',
      '......kkkkkkkkk.',
    ],
  },
  'send': {
    size: 16,
    rows: [
      '................',
      '..............k.',
      '............kkk.',
      '.........kkkwk..',
      '.......kkwwwlk..',
      '.....kkwwwwllk..',
      '...kkwwwwwllk...',
      '.kkwwwwwwlllk...',
      '.kkwwwwwlllk....',
      '...kkkwllllk....',
      '......kllllk....',
      '.......kllk.....',
      '.......kllk.....',
      '........kk......',
      '.........k......',
      '................',
    ],
  },
  'power': {
    size: 16,
    rows: [
      '.......kk.......',
      '....kkkrrkkk....',
      '...krrrwwrrrk...',
      '..krrrrwwrrrrk..',
      '.krrrrrwwrrrrrk.',
      '.krrwwrwwrwwrrk.',
      '.krrwwrwwrwwrrk.',
      'krrwwrrwwrrwwrrk',
      'krrwwrrwwrrwwrrk',
      '.krrwrrrrrrwrrk.',
      '.krrwwrrrrwwrrk.',
      '.krrrwwwwwwrrrk.',
      '..krrrwwwwrrrk..',
      '...krrrrrrrrk...',
      '....kkkrrkkk....',
      '.......kk.......',
    ],
  },
  'restart': {
    size: 16,
    rows: [
      '........k.......',
      '........kk......',
      '.....kkkggk.....',
      '....kggggggk....',
      '...kgggggggk....',
      '..kgggkkggk.....',
      '..kggk..kk......',
      '.kggk...........',
      '.kggk...........',
      '.kggk......kkkk.',
      '.kgggk....kgggk.',
      '..kgggk..kgggk..',
      '..kggggkkggggk..',
      '...kggggggggk...',
      '....kkkggkkk....',
      '.......kk.......',
    ],
  },
  'image': {
    size: 16,
    rows: [
      '................',
      '................',
      'kkkkkkkkkkkkkkkk',
      'kyyyyyyyyyyyyyyk',
      'kykkkkkkkkkkkkyk',
      'kykllllllwwwlkyk',
      'kykllglllwwwlkyk',
      'kyklgwwllwwwlkyk',
      'kykggggglglllkyk',
      'kykggggggggllkyk',
      'kykggggggggglkyk',
      'kykkkkkkkkkkkkyk',
      'kyyyyyyyyyyyyyyk',
      'kkkkkkkkkkkkkkkk',
      '................',
      '................',
    ],
  },
  'desktop': {
    size: 16,
    rows: [
      '................',
      'kkkkkkkkkkkkkkkk',
      'kwwssssssssssssk',
      'kwkkkkkkkkkkkksk',
      'kskllaaaaaaaaksk',
      'ksklaaaaaaaaaksk',
      'kskaaaaaaaaaaksk',
      'kskaaaaaaaaaaksk',
      'kskaaaaaaaaaaksk',
      'kskkkkkkkkkkkksk',
      'ksssssssssssgssk',
      'kkkkkkkkkkkkkkkk',
      '......kssk......',
      '...kkkkkkkkkk...',
      '...kkkkkkkkkk...',
      '................',
    ],
  },
  'start': {
    size: 16,
    rows: [
      '................',
      '..kkkkkkkkkkkk..',
      '.kaaallllllaaak.',
      '.kaalllaalllaak.',
      '.kallalaalallak.',
      '.kllaallllaallk.',
      '.kllllllllllllk.',
      '.klaallwwllaalk.',
      '.klaallwwllaalk.',
      '.kllllllllllllk.',
      '.kllaallllaallk.',
      '.kallalaalallak.',
      '.kaalllaalllaak.',
      '.kaaallllllaaak.',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  },
  'close': {
    size: 16,
    rows: [
      '................',
      '................',
      '................',
      '................',
      '....cc....cc....',
      '.....cc..cc.....',
      '......cccc......',
      '.......cc.......',
      '......cccc......',
      '.....cc..cc.....',
      '....cc....cc....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  'minimize': {
    size: 16,
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '....cccccc......',
      '....cccccc......',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  'maximize': {
    size: 16,
    rows: [
      '................',
      '................',
      '................',
      '...cccccccccc...',
      '...cccccccccc...',
      '...c........c...',
      '...c........c...',
      '...c........c...',
      '...c........c...',
      '...c........c...',
      '...c........c...',
      '...cccccccccc...',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  'restore': {
    size: 16,
    rows: [
      '................',
      '................',
      '................',
      '.....cccccccc...',
      '.....cccccccc...',
      '.....c......c...',
      '...cccccccc.c...',
      '...cccccccc.c...',
      '...c......c.c...',
      '...c......ccc...',
      '...c......c.....',
      '...c......c.....',
      '...cccccccc.....',
      '................',
      '................',
      '................',
    ],
  },
  'check': {
    size: 16,
    rows: [
      '................',
      '................',
      '............kkk.',
      '...........kggk.',
      '..........kggk..',
      '.kkk.....kggk...',
      'kggk....kggk....',
      '.kggk..kggk.....',
      '..kggkkggk......',
      '...kggggk.......',
      '....kggk........',
      '.....kk.........',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  'warning': {
    size: 16,
    rows: [
      '................',
      '................',
      '.......kk.......',
      '......kyyk......',
      '......kyyk......',
      '.....kykkyk.....',
      '.....kykkyk.....',
      '....kyykkyyk....',
      '....kyykkyyk....',
      '...kyyykkyyyk...',
      '...kyyykkyyyk...',
      '..kyyyyyyyyyyk..',
      '..kyyyykkyyyyk..',
      '.kyyyyykkyyyyyk.',
      'kkkkkkkkkkkkkkkk',
      '................',
    ],
  },
  'info': {
    size: 16,
    rows: [
      '.......kk.......',
      '....kkkaakkk....',
      '...kaaaaaaaak...',
      '..kaaaawwaaaak..',
      '.kaaaaawwaaaaak.',
      '.kaaaaaaaaaaaak.',
      '.kaaaawwwaaaaak.',
      'kaaaaaawwaaaaaak',
      'kaaaaaawwaaaaaak',
      '.kaaaaawwaaaaak.',
      '.kaaaaawwaaaaak.',
      '.kaaaaawwaaaaak.',
      '..kaaawwwwaaak..',
      '...kaaaaaaaak...',
      '....kkkaakkk....',
      '.......kk.......',
    ],
  },
  'star': {
    size: 16,
    rows: [
      '................',
      '................',
      '.......kk.......',
      '.......kk.......',
      '.......wk.......',
      '......kwyk......',
      '.kkkkkyyyykkkkk.',
      '..kyyyyyyyyyyk..',
      '...kkyyyyyykk...',
      '.....kyyyyk.....',
      '.....kyyyyk.....',
      '....kyykkyyk....',
      '....kyk..kyk....',
      '....kk....kk....',
      '...k........k...',
      '................',
    ],
  },
  'spider': {
    size: 16,
    rows: [
      '................',
      '.d............d.',
      '.d...k....k...d.',
      '..d...kkk....d..',
      '...d.kwrrw..d...',
      'd...dkrrrk.d...d',
      '.dd..dkrk.d..dd.',
      '...ddkrrrk.dd...',
      '....krkrrkk.....',
      '....krrkkrk.....',
      '...dkrrkkrkdd...',
      '.dd..krrrkd..dd.',
      'd...d.kkk..d...d',
      'd..d........d..d',
      '..d..........d..',
      '..d..........d..',
    ],
  },
  'trophy': {
    size: 16,
    rows: [
      '................',
      '...kkkkkkkkkk...',
      '.kkkwyyyyyyykkk.',
      '.k.kwyyyyyyyk.k.',
      'kk.kywyyyyyyk.kk',
      '.k.kyyyyyyyyk.k.',
      '.kkkkyyyyyykkkk.',
      '....kyyyyyyk....',
      '.....kkyykk.....',
      '.......kk.......',
      '.......kk.......',
      '.......kk.......',
      '....kkkkkkkk....',
      '....kdyyyydk....',
      '....kkkkkkkk....',
      '................',
    ],
  },
  'clock': {
    size: 16,
    rows: [
      '.......kk.......',
      '....kkkaakkk....',
      '...kwwwwwwwwk...',
      '..kwwwwkkwwwwk..',
      '.kwwwwwkkwwwwwk.',
      '.kwwwwwkkwwwwwk.',
      '.kwwwwwkkwwwwwk.',
      'kawwwwwkkwwwwwak',
      'kawwwwwkkkkkwwak',
      '.kwwwwwwwrwwwwk.',
      '.kwwwwwwwwrwwwk.',
      '.kwwwwwwwwwwwwk.',
      '..kwwwwwwwwwwk..',
      '...kwwwwwwwwk...',
      '....kkkaakkk....',
      '.......kk.......',
    ],
  },
  'language': {
    size: 16,
    rows: [
      'kkkkkkkkk.......',
      'kaawwwaak.......',
      'kawaaawak.......',
      'kawaaawak.......',
      'kawwwwwak.......',
      'kawaaawak.......',
      'kawaaawak.......',
      'kaaaaaakkkkkkkkk',
      'kkkkkkkkwwwwaawk',
      '.......kwwwawwwk',
      '.......kwwwwaawk',
      '.......kwwwawwwk',
      '.......kwwawwwwk',
      '.......kwwwaaawk',
      '.......kwwwwwwwk',
      '.......kkkkkkkkk',
    ],
  },
  'calendar': {
    size: 16,
    rows: [
      '................',
      '...kk......kk...',
      '.kkwwkkkkkkwwkk.',
      '.krkkrrrrrrkkrk.',
      '.krrrrrrrrrrrrk.',
      '.kkkkkkkkkkkkkk.',
      '.kwwwwwwwwwwwwk.',
      '.kwswswswswswwk.',
      '.kwwwwwwwwwwwwk.',
      '.kwswswswaawswk.',
      '.kwwwwwwwaawwwk.',
      '.kwswswswswswwk.',
      '.kwwwwwwwwwwwwk.',
      '.kwswswwwwwwwwk.',
      '.kwwwwwwwwwwwwk.',
      '.kkkkkkkkkkkkkk.',
    ],
  },
  'chip': {
    size: 16,
    rows: [
      '................',
      '....s.s..s.s....',
      '....s.s..s.s....',
      '..kkkkkkkkkkkk..',
      'sskwdddddddddkss',
      '..kddddddddddk..',
      'sskdddaaaadddkss',
      '..kdddalladddk..',
      '..kdddalladddk..',
      'sskdddaaaadddkss',
      '..kddddddddddk..',
      'sskddddddddddkss',
      '..kkkkkkkkkkkk..',
      '....s.s..s.s....',
      '....s.s..s.s....',
      '................',
    ],
  },
  'pin': {
    size: 16,
    rows: [
      '.......kk.......',
      '.....kkrrkk.....',
      '....krrrrrrk....',
      '...krwrrrrrrk...',
      '...kwrkkkkrrk...',
      '..krrrkwwkrrrk..',
      '..krrrkwwkrrrk..',
      '...krrkkkkrrk...',
      '...krrrrrrrrk...',
      '....krrrrrrk....',
      '.....krrrrk.....',
      '......krrk......',
      '......krrk......',
      '.......kk.......',
      '.......kk.......',
      '................',
    ],
  },
};
