'use client';

import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { animate, motion, useMotionValue, useReducedMotion, useTransform } from 'framer-motion';
import type { AnimationPlaybackControls } from 'framer-motion';
import { SpeechBubble } from './SpeechBubble';
import { useMascot } from '@/context/MascotContext';
import { useWindowManager, type WindowId, type WindowState } from '@/context/WindowManagerContext';
import { useIsMobile } from '@/lib/hooks/useIsMobile';
import { asset } from '@/lib/asset';

export type SpiderFrame =
  | 'idle'
  | 'blink'
  | 'loading'
  | 'celebrating'
  | 'sleeping'
  | 'typing'
  | 'waving'
  | 'swinging';

const FRAMES: SpiderFrame[] = ['idle', 'blink', 'loading', 'celebrating', 'sleeping', 'typing', 'waving', 'swinging'];

// Mirrors public/mascot/frames.json (generated by scripts/mascot/build_frames.py).
// `frames` loop at `fps`; `stripFrames` is the total width of the strip when it
// carries extra cut-in frames (idle's blink at `blinkFrame`).
interface StripMeta {
  frames: number;
  fps: number;
  stripFrames?: number;
  blinkFrame?: number;
}

const DEFAULT_MANIFEST: Record<SpiderFrame, StripMeta> = {
  idle: { frames: 4, fps: 4, blinkFrame: 4, stripFrames: 5 },
  blink: { frames: 4, fps: 4 },
  loading: { frames: 4, fps: 8 },
  celebrating: { frames: 4, fps: 6 },
  sleeping: { frames: 4, fps: 3 },
  typing: { frames: 4, fps: 8 },
  waving: { frames: 6, fps: 6 },
  swinging: { frames: 4, fps: 8 },
};

const stripTotal = (m: StripMeta) => m.stripFrames ?? m.frames;

// Background-position (in %) that shows frame `k` of a strip `total` frames wide.
const framePos = (k: number, total: number) => (total > 1 ? (k / (total - 1)) * 100 : 0);

const isStripMeta = (v: unknown): v is StripMeta => {
  if (!v || typeof v !== 'object') return false;
  const m = v as Record<string, unknown>;
  return (
    typeof m.frames === 'number' &&
    m.frames >= 1 &&
    typeof m.fps === 'number' &&
    m.fps > 0 &&
    (m.stripFrames === undefined || (typeof m.stripFrames === 'number' && m.stripFrames >= m.frames)) &&
    (m.blinkFrame === undefined || typeof m.blinkFrame === 'number')
  );
};

// Window perch tuning (desktop only).
const SPRITE_PX = 112; // md:w-28
const PERCH_EVERY_MS = 40_000;
const PERCH_STAY_MS = 8_000;
const PERCH_CHANCE = 0.6;
const TITLEBAR_BUTTONS_PX = 96; // keeps the sprite left of _ □ ✕
const FEET_OVERLAP_PX = 12; // sprite has ~8px transparent padding under the feet
const THREAD_ANCHOR_PX = 22; // where the web thread meets the head (from sprite top)
const BUBBLE_ROOM_PX = 110; // space needed above the sprite for the bubble

const EASE_OUT: [number, number, number, number] = [0.22, 1, 0.36, 1];

type Phase = 'corner' | 'dropping' | 'perched' | 'returning';

const rectKey = (w: WindowState) => `${w.position.x},${w.position.y},${w.size.width},${w.size.height}`;

export const PixelSpider: React.FC = () => {
  const mascot = useMascot();
  const { windows, activeWindowId } = useWindowManager();
  const shouldReduceMotion = useReducedMotion();
  const isMobile = useIsMobile();

  const [manifest, setManifest] = useState<Record<SpiderFrame, StripMeta>>(DEFAULT_MANIFEST);
  const [stripReady, setStripReady] = useState<Partial<Record<SpiderFrame, boolean>>>({});
  const [isBlinking, setIsBlinking] = useState(false);
  const [phase, setPhaseState] = useState<Phase>('corner');
  const [perchTop, setPerchTop] = useState(0);

  const phaseRef = useRef<Phase>('corner');
  const setPhase = useCallback((p: Phase) => {
    phaseRef.current = p;
    setPhaseState(p);
  }, []);

  // ---------------------------------------------------------------- assets
  // Load the generated manifest (falls back to the built-in copy) and preload
  // every strip + the single-frame fallbacks. A strip that fails to load keeps
  // its mood on the plain `-01.png`.
  useEffect(() => {
    const ctrl = new AbortController();
    fetch(asset('/mascot/frames.json'), { signal: ctrl.signal })
      .then((r) => (r.ok ? r.json() : null))
      .then((json: unknown) => {
        if (!json || typeof json !== 'object') return;
        const data = json as Record<string, unknown>;
        setManifest((prev) => {
          const next = { ...prev };
          FRAMES.forEach((f) => {
            if (isStripMeta(data[f])) next[f] = data[f] as StripMeta;
          });
          return next;
        });
      })
      .catch(() => undefined);

    const imgs: HTMLImageElement[] = [];
    FRAMES.forEach((f) => {
      const single = new Image();
      single.src = asset(`/mascot/${f}-01.png`);
      imgs.push(single);

      const strip = new Image();
      strip.onload = () => setStripReady((s) => ({ ...s, [f]: true }));
      strip.src = asset(`/mascot/${f}-strip.png`);
      imgs.push(strip);
    });

    return () => {
      ctrl.abort();
      imgs.forEach((img) => {
        img.onload = null;
      });
    };
  }, []);

  const keyframesCss = useMemo(
    () =>
      FRAMES.map((f) => {
        const m = manifest[f];
        const total = stripTotal(m);
        if (total < 2 || m.frames < 2) return '';
        return `@keyframes pspider-${f}{from{background-position:0% 0}to{background-position:${framePos(
          m.frames,
          total
        )}% 0}}`;
      }).join(''),
    [manifest]
  );

  // ---------------------------------------------------------------- blink
  const idleBlinkFrame = manifest.idle.blinkFrame;
  const canBlink = mascot.frame === 'idle' && !shouldReduceMotion && !!stripReady.idle && idleBlinkFrame !== undefined;
  useEffect(() => {
    if (!canBlink) return;
    let blinkTimeout: ReturnType<typeof setTimeout> | undefined;
    const interval = setInterval(() => {
      setIsBlinking(true);
      blinkTimeout = setTimeout(() => setIsBlinking(false), 160);
    }, 4000);
    return () => {
      clearInterval(interval);
      if (blinkTimeout) clearTimeout(blinkTimeout);
      setIsBlinking(false);
    };
  }, [canBlink]);

  const { setSpeechText } = mascot;
  const dismissSpeech = useCallback(() => setSpeechText(undefined), [setSpeechText]);

  // ---------------------------------------------------------------- motion
  const mx = useMotionValue(0);
  const my = useMotionValue(0);
  const rot = useMotionValue(0);
  const holderRef = useRef<HTMLDivElement>(null);
  const cornerTopRef = useRef(0);
  // Thread runs from the top of the screen to the spider's head.
  const threadHeight = useTransform(my, (v) => Math.max(0, cornerTopRef.current + v + THREAD_ANCHOR_PX));

  const controlsRef = useRef<AnimationPlaybackControls[]>([]);
  const stayTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const perchRef = useRef<{ id: WindowId; key: string } | null>(null);

  const stopMotion = useCallback(() => {
    controlsRef.current.forEach((c) => c.stop());
    controlsRef.current = [];
    if (stayTimerRef.current) {
      clearTimeout(stayTimerRef.current);
      stayTimerRef.current = null;
    }
  }, []);

  const snapToCorner = useCallback(() => {
    stopMotion();
    perchRef.current = null;
    mx.set(0);
    my.set(0);
    rot.set(0);
    setPhase('corner');
  }, [stopMotion, mx, my, rot, setPhase]);

  // Clean up any running animation/timer on unmount.
  useEffect(() => stopMotion, [stopMotion]);

  const returnToCorner = useCallback(() => {
    if (phaseRef.current === 'corner' || phaseRef.current === 'returning') return;
    stopMotion();
    perchRef.current = null;
    setPhase('returning');
    const y0 = my.get();
    const opts = { duration: 1.1, ease: EASE_OUT };
    controlsRef.current = [
      animate(mx, 0, opts),
      animate(my, [y0, Math.max(y0 - 60, -cornerTopRef.current), 0], { ...opts, times: [0, 0.35, 1] }),
      animate(rot, [0, 14, -8, 0], { duration: 1.1, ease: 'easeInOut' }),
    ];
    controlsRef.current[0].then(() => {
      if (phaseRef.current === 'returning') setPhase('corner');
    });
  }, [stopMotion, mx, my, rot, setPhase]);

  const startPerch = useCallback(
    (w: WindowState) => {
      const el = holderRef.current;
      if (!el || phaseRef.current !== 'corner') return;
      const rect = el.getBoundingClientRect();
      const targetLeft = w.position.x + w.size.width - TITLEBAR_BUTTONS_PX - SPRITE_PX;
      const targetTop = w.position.y + FEET_OVERLAP_PX - SPRITE_PX;
      if (
        targetTop < 24 ||
        targetLeft < w.position.x + 8 ||
        targetLeft < 8 ||
        targetLeft + SPRITE_PX > window.innerWidth - 8
      ) {
        return;
      }
      const dx = targetLeft - rect.left;
      const dy = targetTop - rect.top;
      cornerTopRef.current = rect.top;
      perchRef.current = { id: w.id, key: rectKey(w) };
      setPerchTop(targetTop);
      setPhase('dropping');

      // Travel up and over to above the title bar, then drop down the thread.
      const peak = Math.max(dy - 90, -rect.top);
      const opts = { duration: 1.4, times: [0, 0.6, 1], ease: 'easeInOut' as const };
      controlsRef.current = [animate(mx, [0, dx, dx], opts), animate(my, [0, peak, dy], opts)];
      controlsRef.current[1].then(() => {
        if (phaseRef.current !== 'dropping') return;
        setPhase('perched');
        stayTimerRef.current = setTimeout(returnToCorner, PERCH_STAY_MS);
      });
    },
    [mx, my, setPhase, returnToCorner]
  );

  const perchAllowed = !isMobile && !shouldReduceMotion;
  const activeWin = activeWindowId ? windows[activeWindowId] : null;
  const latest = useRef({ activeWin, frame: mascot.frame, isSwinging: mascot.isSwinging });
  latest.current = { activeWin, frame: mascot.frame, isSwinging: mascot.isSwinging };

  // Every ~40s the spider may drop onto the active window's title bar.
  useEffect(() => {
    if (!perchAllowed) return;
    const id = setInterval(() => {
      if (phaseRef.current !== 'corner' || document.hidden) return;
      const { activeWin: w, frame, isSwinging } = latest.current;
      if (!w || !w.isOpen || w.isMinimized || w.isMaximized || frame !== 'idle' || isSwinging) return;
      if (Math.random() > PERCH_CHANCE) return;
      startPerch(w);
    }, PERCH_EVERY_MS);
    return () => clearInterval(id);
  }, [perchAllowed, startPerch]);

  // Reduced motion / phone layout: no perching, sit in the corner.
  useEffect(() => {
    if (!perchAllowed && phaseRef.current !== 'corner') snapToCorner();
  }, [perchAllowed, snapToCorner]);

  // If the perch window moves, resizes, closes, minimizes, maximizes or loses focus, head home.
  useEffect(() => {
    if (phase !== 'dropping' && phase !== 'perched') return;
    const p = perchRef.current;
    if (!p) return;
    const w = windows[p.id];
    if (activeWindowId !== p.id || !w || !w.isOpen || w.isMinimized || w.isMaximized || rectKey(w) !== p.key) {
      returnToCorner();
    }
  }, [windows, activeWindowId, phase, returnToCorner]);

  // Browser resize while away from the corner: the corner moved, go back.
  useEffect(() => {
    if (phase === 'corner') return;
    const onResize = () => snapToCorner();
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, [phase, snapToCorner]);

  // Click-triggered swing arc (only from the corner).
  const allowSwing = mascot.isSwinging && !isMobile && !shouldReduceMotion && phase === 'corner';
  useEffect(() => {
    if (!allowSwing) return;
    const el = holderRef.current;
    if (el) cornerTopRef.current = el.getBoundingClientRect().top;
    const opts = { duration: 1.2, ease: EASE_OUT };
    const ctrls = [
      animate(mx, [0, -80, 0], opts),
      animate(my, [0, -140, 0], opts),
      animate(rot, [0, -20, 20, 0], opts),
    ];
    return () => {
      ctrls.forEach((c) => c.stop());
      mx.set(0);
      my.set(0);
      rot.set(0);
    };
  }, [allowSwing, mx, my, rot]);

  // ---------------------------------------------------------------- render
  // On phones the app sheets cover the screen, so the mascot steps aside while one is open.
  const anyWindowVisible = Object.values(windows).some((w) => w.isOpen && !w.isMinimized);
  if (isMobile && anyWindowVisible) return null;

  const frame: SpiderFrame = phase === 'returning' ? 'swinging' : mascot.frame;
  const meta = manifest[frame];
  const total = stripTotal(meta);
  const useStrip = !!stripReady[frame] && total > 1;
  const showBlink = frame === 'idle' && isBlinking && meta.blinkFrame !== undefined;
  const animated = useStrip && !shouldReduceMotion && !showBlink && meta.frames > 1;

  const spriteStyle: React.CSSProperties = useStrip
    ? {
        backgroundImage: `url(${asset(`/mascot/${frame}-strip.png`)})`,
        backgroundSize: `${total * 100}% 100%`,
        backgroundRepeat: 'no-repeat',
        backgroundPosition: `${showBlink ? framePos(meta.blinkFrame as number, total) : 0}% 0`,
        animation: animated ? `pspider-${frame} ${meta.frames / meta.fps}s steps(${meta.frames}) infinite` : 'none',
        imageRendering: 'pixelated',
      }
    : {
        backgroundImage: `url(${asset(`/mascot/${frame}-01.png`)})`,
        backgroundSize: '100% 100%',
        backgroundRepeat: 'no-repeat',
        imageRendering: 'pixelated',
      };

  const showThread = phase === 'dropping' || phase === 'perched' || allowSwing;
  const perchedish = phase === 'dropping' || phase === 'perched';
  // When perched near the top of the screen there's no room above: put the bubble to the left.
  const bubbleBeside = perchedish && perchTop < BUBBLE_ROOM_PX;

  return (
    <div className="fixed bottom-16 md:bottom-12 right-3 md:right-6 z-[750] pointer-events-none">
      <style>{keyframesCss}</style>
      <motion.div ref={holderRef} style={{ x: mx, y: my }} className="relative w-16 h-16 md:w-28 md:h-28">
        {showThread && (
          <motion.div
            aria-hidden="true"
            className="absolute left-[calc(50%-1px)] w-[2px] bg-spidey/80 pointer-events-none"
            style={{ height: threadHeight, bottom: `calc(100% - ${THREAD_ANCHOR_PX}px)` }}
          />
        )}

        {mascot.speechText && (
          <div
            className={`absolute flex justify-end w-[min(16rem,calc(100vw-24px))] md:w-[240px] ${
              bubbleBeside ? 'right-full bottom-1/2 mr-2' : 'bottom-full right-0 mb-2'
            }`}
          >
            <div className="pointer-events-auto max-w-full">
              <SpeechBubble text={mascot.speechText} onDismiss={dismissSpeech} />
            </div>
          </div>
        )}

        <motion.button
          type="button"
          aria-label="Pixel Spider mascot — click for a tip"
          onClick={(e) => {
            e.stopPropagation();
            mascot.triggerRandomInteraction();
          }}
          style={{ rotate: rot }}
          className="relative block w-full h-full group select-none pointer-events-auto"
        >
          {phase === 'corner' && (
            <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-12 md:w-16 h-3 bg-black/40 rounded-full blur-[2px]" />
          )}
          <div
            aria-hidden="true"
            style={spriteStyle}
            className="relative w-full h-full pixel-art drop-shadow-md group-hover:scale-105 transition-transform"
          />
        </motion.button>
      </motion.div>
    </div>
  );
};
